name: Java CI with Maven

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the action on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Set up Java 11 for building the project

    - name: Build with Maven
      run: mvn clean install  # Use Maven to compile the code

    - name: Run tests with Maven
      run: mvn test  # Run the unit tests with Maven
